### ISSUE TITLE
Sorting doesn't work in GridView

### ISSUE THREAD

**Issue by nagyt234** [2amigos/yii2-translateable-behavior#4]
Sorting on internationalized fields doesn't work in GridView. The fields in the table header are simple text fields, no links.

Any idea?

**Comment by bethrezen** [comment]
It'll be better if you post DataProvider initialization code and widget code

**Comment by nagyt234** [comment]
I've made seom progress but I get an exception if the index action is called:
```
2015-01-30 15:47:47 [192.168.3.1][-][-][error][yii\base\ErrorException:8] exception 'yii\base\ErrorException' with message 'Array to string conversion' in /var/www/dev/recipes/vendor/yiisoft/yii2/helpers/BaseHtml.php:487
Stack trace:
#0 /var/www/dev/recipes/vendor/yiisoft/yii2/helpers/BaseHtml.php(487): yii\base\ErrorHandler->handleError(8, 'Array to string...', '/var/www/dev/re...', 487, Array)
#1 /var/www/dev/recipes/vendor/yiisoft/yii2/helpers/BaseHtml.php(1143): yii\helpers\BaseHtml::input('text', 'IngredientGroup...', Array, Array)
#2 /var/www/dev/recipes/vendor/yiisoft/yii2/helpers/BaseHtml.php(1160): yii\helpers\BaseHtml::activeInput('text', Object(app\models\IngredientGroupSearch), 'translations', Array)
#3 /var/www/dev/recipes/vendor/yiisoft/yii2/grid/DataColumn.php(165): yii\helpers\BaseHtml::activeTextInput(Object(app\models\IngredientGroupSearch), 'translations', Array)
#4 /var/www/dev/recipes/vendor/yiisoft/yii2/grid/Column.php(112): yii\grid\DataColumn->renderFilterCellContent()
#5 /var/www/dev/recipes/vendor/yiisoft/yii2/grid/GridView.php(397): yii\grid\Column->renderFilterCell()
#6 /var/www/dev/recipes/vendor/yiisoft/yii2/grid/GridView.php(362): yii\grid\GridView->renderFilters()
#7 /var/www/dev/recipes/vendor/yiisoft/yii2/grid/GridView.php(294): yii\grid\GridView->renderTableHeader()
#8 /var/www/dev/recipes/vendor/yiisoft/yii2/widgets/BaseListView.php(140): yii\grid\GridView->renderItems()
#9 /var/www/dev/recipes/vendor/yiisoft/yii2/grid/GridView.php(264): yii\widgets\BaseListView->renderSection('{items}')
#10 /var/www/dev/recipes/vendor/yiisoft/yii2/widgets/BaseListView.php(117): yii\grid\GridView->renderSection('{items}')
#11 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array)
#12 /var/www/dev/recipes/vendor/yiisoft/yii2/widgets/BaseListView.php(120): preg_replace_callback('/{\w+}/', Object(Closure), '{summary}?{item...')
#13 /var/www/dev/recipes/vendor/yiisoft/yii2/grid/GridView.php(239): yii\widgets\BaseListView->run()
#14 /var/www/dev/recipes/vendor/yiisoft/yii2/base/Widget.php(96): yii\grid\GridView->run()
#15 /var/www/dev/recipes/views/ingredient-group/index.php(36): yii\base\Widget::widget(Array)
#16 /var/www/dev/recipes/vendor/yiisoft/yii2/base/View.php(325): require('/var/www/dev/re...')
#17 /var/www/dev/recipes/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/var/www/dev/re...', Array)
#18 /var/www/dev/recipes/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/var/www/dev/re...', Array, Object(app\controllers\IngredientGroupController))
#19 /var/www/dev/recipes/vendor/yiisoft/yii2/base/Controller.php(367): yii\base\View->render('index', Array, Object(app\controllers\IngredientGroupController))
#20 /var/www/dev/recipes/controllers/IngredientGroupController.php(41): yii\base\Controller->render('index', Array)
#21 [internal function]: app\controllers\IngredientGroupController->actionIndex()
#22 /var/www/dev/recipes/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#23 /var/www/dev/recipes/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#24 /var/www/dev/recipes/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('', Array)
#25 /var/www/dev/recipes/vendor/yiisoft/yii2/web/Application.php(83): yii\base\Module->runAction('ingredient-grou...', Array)
#26 /var/www/dev/recipes/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#27 /var/www/dev/recipes/index.php(12): yii\base\Application->run()
#28 {main}
```
I have IngredientGroup and IngredientGroupSearch models, and CRUD views, all generated with the default gii and modified to have IngredientGroup.name internationalized with yii2-translateable-behavior.

models/IngredientGroup.php:
```php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use dosamigos\translateable\TranslateableBehavior;

/**
 * This is the model class for table "{{%ingredient_group}}".
 *
 * @property integer $id
 * @property string $FdGrp_CD
 * @property string $name       
 * @property integer $created_at
 * @property integer $updated_at
 */
class IngredientGroup extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%ingredient_group}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            'translation' => [
                'class' => TranslateableBehavior::className(),
                'translationAttributes' => [
                    'name',
                ]
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['FdGrp_CD', 'name'], 'required'],
            [['FdGrp_CD'], 'string', 'max' => 10],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'FdGrp_CD' => 'FdGrp_CD',
//            'name' => Yii::t('app', 'Name'),
        ];
    }

    /**
    * @return \yii\db\ActiveQuery
    */
    public function getTranslations()
    {
        return $this->hasMany(IngredientGroupLang::className(), ['ingredient_group_id' => 'id']);
    }
}
```
models/IngredientGroupSearch.php:
```php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\IngredientGroup;

/**
 * IngredientGroupSearch represents the model behind the search form about `app\models\IngredientGroup`.
 */
class IngredientGroupSearch extends IngredientGroup
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['FdGrp_CD', 'name'], 'safe'],
            [['translations'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = IngredientGroup::find();

        $query->joinWith(['translations']);

//      $query->andWhere(['{{%ingredient_group_lang}}.language' => \Yii::$app->language]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $dataProvider->sort->attributes['translations'] = [
          'asc'  => ['{{%ingredient_group_lang}}.name' => SORT_ASC ],
          'desc' => ['{{%ingredient_group_lang}}.name' => SORT_DESC],
        ];

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        $query->andFilterWhere([
            'id' => $this->id,
        ]);

        $query->andFilterWhere(['like', 'FdGrp_CD', $this->FdGrp_CD])
            ->andFilterWhere(['like', 'name', $this->name]);

        return $dataProvider;
    }
}
```
views/ingredient-group/index.php:
```php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\IngredientGroupSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Ingredient Groups');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ingredient-group-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create {modelClass}', [
    'modelClass' => 'Ingredient Group',
]), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
          
            'id',
            'FdGrp_CD',
            ['attribute' => 'translations', 'value' => 'translations.name'],
        
            ['class' => 'yii\grid\ActionColumn'],
        ],   
    ]); ?>

</div> 
```

**Comment by nagyt234** [comment]
Success! The problem caused by the hasMany relation. Only hasOne relation can be used in GridView's column setting (the relation should return a record not an array):

views/ingredient-group/index.php:
```php
...
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'FdGrp_CD',
            ['attribute' => 'name', 'value' => 'translation.name'],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
...
```
models/IngredientGroupSearch.php:
```php
...
        $query->joinWith(['translation']);
...
```
models/IngredientGroup.php:
```php
...
    public function rules()
    {
        return [
            [['FdGrp_CD', 'name'], 'required'],
            [['FdGrp_CD'], 'string', 'max' => 10],
            [['name'], 'string', 'max' => 255]
        ];
    }
...
    /**
    * @return \yii\db\ActiveQuery
    */
    public function getTranslation()
    {
        return $this->hasOne(IngredientGroupLang::className(), ['ingredient_group_id' => 'id'])->
                      andWhere(['{{%ingredient_group_lang}}.language' => \Yii::$app->language]);
    }
...
```

**Comment by tonydspaniard** [comment]
@nagyt234 good work!
